export enum RabbitMQ {
    OrderQueue = 'orders',
    IngredientQueue = 'ingredients',
    RecipeQueue = 'recipes'
}


export enum IngredientMSG {
    CREATE = 'CREATE_INGREDIENT',
    FIND_ALL = 'FIND_INGREDIENTS',
    FIND_ONE = 'FIND_INGREDIENT',
    UPDATE = 'UPDATE_INGREDIENT',
    UPDATE5 = 'UPDATE5_INGREDIENT',
    DELETE = 'DELETE_INGREDIENT',
    DELETE_SHOPPING = 'DELETE_SHOPPING_INGREDIENT',
    FIND_ONE_BY_NAME = 'FIND_INGREDIENTE_BY_NAME',
    GET_INGREDIENTS = 'GET_INGREDIENTS',
    GET_SHOPPING_INGREDIENTS = 'GET_SHOPPING_INGREDIENTS'
}

export enum RecipeMSG {
    CREATE = 'CREATE_RECIPE',
    FIND_ALL = 'FIND_RECIPES',
    FIND_ONE = 'FIND_RECIPE_BY_ID',
    UPDATE = 'UPDATE_RECIPE',
    DELETE = 'DELETE_RECIPE',
    ADD_INGREDIENT = 'ADD_INGREDIENT_TO_RECIPE',
    FIND_ONE_RANDOM = 'FIND_RECIPE_RANDOM',
    COOK = 'COOK RECIPE',
    REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS'
}

export enum OrderMSG{
    CREATE = 'CREATE_ORDER',
    FIND_ALL = 'FIND_ORDERS',
    FIND_ONE = 'FIND_ORDER',
    FIND_NUMBER_ORDER = 'FIND_NUMBER_ORDER',
    UPDATE = 'UPDATE_ORDER',
    DELETE = 'DELETE_ORDER',
    DELETE_ALL = 'DELETE_ALL_ORDER',
    NOT_DELIVERED = 'NOT_DELIVERED_ORDERS',
    DELIVERED = 'DELIVERED_ORDERS'
}